### ISSUE TITLE
problem with running a hologram generation and reconstruction animation

### ISSUE THREAD

**Issue by Drachenbauer** [rafael-fuente/diffractsim#62]
It looked like the command `python setup.py install` from in the repo-main folder worked and installed something.

But trying to run a hologram generation and reconstruction animation from the examples said, that i still not had CUDA and CuPy.

so i installed CUDA and CuPy.
But now a new error occured at trying to launch a hologram generation and reconstruction animation:

```
PS F:\Mods\diffractsim-main\diffractsim-main\examples> python phase_hologram_kite_generation_and_reconstruction.py
Traceback (most recent call last):
  File "F:\Mods\diffractsim-main\diffractsim-main\examples\phase_hologram_kite_generation_and_reconstruction.py", line 9, in <module>
    PR.retrieve_phase_mask(max_iter = 200, method = 'Conjugate-Gradient')
  File "F:\Program Files\Python312\Lib\site-packages\diffractsim-2.2.7-py3.12.egg\diffractsim\holography\fourier_phase_retrieval.py", line 91, in retrieve_phase_mask
    target_amplitude = bd.array(resize_array(self.target_amplitude, (self.Ny + 2 * self.Ny//2 , self.Nx + 2 * self.Nx//2)))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Program Files\Python312\Lib\site-packages\diffractsim-2.2.7-py3.12.egg\diffractsim\util\image_handling.py", line 63, in resize_array
    fun = interp2d(
          ^^^^^^^^^
  File "F:\Program Files\Python312\Lib\site-packages\scipy-1.15.0rc1-py3.12-win-amd64.egg\scipy\interpolate\_interpolate.py", line 129, in __init__
    raise NotImplementedError(err_mesg)
NotImplementedError: `interp2d` has been removed in SciPy 1.14.0.

For legacy code, nearly bug-for-bug compatible replacements are
`RectBivariateSpline` on regular grids, and `bisplrep`/`bisplev` for
scattered 2D data.

In new code, for regular grids use `RegularGridInterpolator` instead.
For scattered data, prefer `LinearNDInterpolator` or
`CloughTocher2DInterpolator`.

For more details see
https://scipy.github.io/devdocs/tutorial/interpolate/interp_transition_guide.html
```
I simply made a copy of the existing hologram file in the examples and replaced the filename of the used aperture-file with my own kite-shaped one, that i added to the Apertures folder.

What else do i miss in order to get that to work?

**Comment by InTheory7** [comment]
I've got the same issue. The error message is saying that the interp2d function has been removed from SciPy so it fails when called by the retrieve_phase_mask() method.

**Comment by InTheory7** [comment]
I'm not sure if this is literally a one-to-one replacement, but if you replace this section in the `resize_array()` method in `image_handling.py`:

```
from scipy.interpolate import interp2d
    fun = interp2d(
        np.linspace(0, 1, Nx),
        np.linspace(0, 1, Ny),
        img_array,
        kind="cubic",
    )
```

with this...

```
from scipy.interpolate import RectBivariateSpline
    fun = RectBivariateSpline(
        np.linspace(0, 1, Nx),
        np.linspace(0, 1, Ny),
        img_array,
        #kind="cubic",
    )
```

(The `kind` line can be removed/commented out as above as the spline is always cubic) then it works again.

**Comment by rafael-fuente** [comment]
Hi, the problem is solved. As [InTheory7](https://github.com/InTheory7) mentioned, interp2d must be replaced with RectBivariateSpline when using the new versions of SciPy

**Comment by Drachenbauer** [comment]
When i now run such a simulation, i get a window with a dark red square and when i close it a window with an image of the used aperture in the same dark red.
But that does not look very much like a hologram.

**Comment by rafael-fuente** [comment]
> When i now run such a simulation, i get a window with a dark red square and when i close it a window with an image of the used aperture in the same dark red. But that does not look very much like a hologram.

Can you show your script and let me check what is happening?
For example, `phase_hologram_github_logo_generation_and_reconstruction.py` is working correctly

**Comment by Drachenbauer** [comment]
I get this:
![Image](https://github.com/user-attachments/assets/ad5e607e-1317-444b-a8ef-d6ac61377832)

from this aperture:
![Image](https://github.com/user-attachments/assets/bbf61106-2972-45d9-a4a8-95c09a57eb11)

In your readme i saw fancy rainbowy images, so i taught, it would look more like that.
