### ISSUE TITLE
Running rectangular slit with CPU

### ISSUE THREAD

**Issue by Abhisek1300** [rafael-fuente/diffractsim#9]
Running rectangular slit with CPU gives me the following error-
_AttributeError: 'RectangularSlit' object has no attribute 'xx'_

[rectangular_slit.zip](https://github.com/rafael-fuente/diffractsim/files/7799674/rectangular_slit.zip)

[I have attached the code I'm running]
complete traceback-

Traceback (most recent call last):

  File "<ipython-input-54-bfe6ec54ae0d>", line 1, in <module>
    runfile('C:/Users/acer/Desktop/python-sonu/programms/rectangular_slit.py', wdir='C:/Users/acer/Desktop/python-sonu/programms')

  File "C:\Users\acer\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\acer\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/acer/Desktop/python-sonu/programms/rectangular_slit.py", line 15, in <module>
    F.add(RectangularSlit(width= 1*mm, height=5*cm,x0=0,y0=0))

  File "C:\Users\acer\Anaconda3\lib\site-packages\diffractsim\monochromatic_simulator.py", line 51, in add
    self.E = optical_element.get_E(self.E, self.xx, self.yy, self.λ)

  File "C:\Users\acer\Anaconda3\lib\site-packages\diffractsim\diffractive_elements\diffractive_element.py", line 18, in get_E
    return E*self.get_transmittance(xx, yy, λ)

  File "C:\Users\acer\Anaconda3\lib\site-packages\diffractsim\diffractive_elements\rectangular_slit.py", line 25, in get_transmittance
    bd.ones_like(self.xx), bd.zeros_like(self.xx))

AttributeError: 'RectangularSlit' object has no attribute 'xx
[rectangular_slit.zip](https://github.com/rafael-fuente/diffractsim/files/7799672/rectangular_slit.zip)
'

**Comment by rafael-fuente** [comment]
It was because a typo I commited in the new version update. Thank you for noticing it! It's corrected by now. Reinstall the package.

Note: For adding a custom text to the plots as you seem to want to use only the `text` argument. This is a modification of the script you attached to achieve that:

```python
import diffractsim
import numpy as np
diffractsim.set_backend("CPU") #Change the string to "CUDA" to use GPU acceleration

from diffractsim import MonochromaticField, mm, nm, cm, RectangularSlit
wl1= 632.8
for ri in np.arange(1,1.1,0.05):
    wl=wl1/ri
    print(ri)

    F = MonochromaticField(
        wavelength=wl * nm, extent_x=18 * mm, extent_y=18 * mm, Nx=1024, Ny=1024
    )
    
    F.add(RectangularSlit(width= 1*mm, height=5*cm,x0=0,y0=0))
    #for i in range(20):
    F.propagate(74*cm)
    rgb = F.get_colors()
    g= F.plot_colors(rgb, xlim=[-7* mm, 7* mm], ylim=[-7* mm, 7* mm], text= "RI = {}".format("%.3f" % ri))
```

**Comment by Abhisek1300** [comment]
Thanks!! The RectangularSlit is working properly now!! 
And, yes I had to label the Refractive index too in the plot, so i had to change the .plot_colors() a little!!
